project:
  type: website
  output-dir: docs

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

website:
  title: "Lukman Jibril Aliyu"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Certifications"
        href: certifications.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Blog"
        href: blog.qmd
  page-footer: "© 2025 Lukman Jibril Aliyu"
