---
title: "Lukman Jibril Aliyu"
---

# Welcome to My Personal Website

My name is Lukman Jibril Aliyu, and I am a pharmacist dedicated to advancing Biomedical Informatics and Artificial Intelligence (AI) to improve healthcare outcomes. My work lies at the intersection of healthcare, technology, and data, aiming to develop innovative solutions that address critical challenges in healthcare delivery, particularly in underserved areas.

This website showcases my projects, publications, and the journey that has taken me from pharmacy practice to the forefront of Biomedical Informatics, Natural Language Processing (NLP), and AI. My research spans Global Health, Epidemiology, and Biostatistics, with a strong focus on data-driven innovations. Notably, my work in NLP includes developing language technologies for underrepresented languages like Hausa and leveraging AI to improve clinical text processing and understanding.

From improving medical supply chains and logistics, to modeling disease dynamics, to applying biostatistical methods for personalized interventions, my focus remains on creating impactful, scalable solutions for real-world health challenges.

I invite you to explore my projects, publications, and NLP research contributions to learn more about my passion for harnessing technology to build a healthier world.

[Learn more about me](about.qmd)


---

## Latest Updates

- **February 2026**: My Deep Learning Indaba, Rwanda 2025 paper has finally been published. Find it [here](https://proceedings.mlr.press/v302/aliyu26a.html).
- **October 2025**: Honored to be recognized by DeepLearning.AI for contributing to the testing of Andrew Ng’s new Agentic AI Course, helping refine and enhance its quality ahead of launch. Details on my blog [post](https://lukmanaj.github.io/ailearningloop/posts/agentic-ai-test/).
- **August 2025**: I presented our [paper](https://arxiv.org/abs/2507.21364) at the Deep Learning Indaba 2025, in Kigali, Rwanda.
- **July 2025**: Our [paper](https://openreview.net/pdf?id=OfYBVdUUez), my first first-author paper, titled `Evaluating Deep Learning Models for African Wildlife Image Classification: From DenseNet to Vision Transformers` was accepted by Deep Learning Indaba 2025.
- **April 2025**: Our [paper](https://openreview.net/pdf?id=j9CCM7NDAO) titled `Who Wrote This? Identifying Machine vs Human-Generated Text in Hausa` was accepted by AfricaNLP 2025.
- **March 2025**: Recognized as best tester for the first course of the `DeepLearning.AI` Data Analytics Professional Certificate. I was also selected as a course mentor.
- **February 2025**: Our [paper](https://www.frontiersin.org/journals/pharmacology/articles/10.3389/fphar.2025.1531141/full) titled `Leveraging AI to Optimize Vaccines Supply Chain and Logistics in Africa: Opportunities and Challenges` was published. 
- **December 2024**: Our [paper](https://narrax.org/main/article/view/180) titled `Enhancing primary healthcare delivery in Nigeria through the adoption of advanced technologies`  was published. 
- **November 2024**: Featured across all `DeepLearning.AI` social media platforms for my remarkable journey integrating AI into my professional practice, as documented in my [blog article](https://lukmanaj.github.io/ailearningloop/posts/dlai-feature/)
- **September 2024**: Won 3rd place in the Data Science for Health Ideathon at the Deep Learning Indaba, 2024. 
- **August 2024**: Earned the "Devotee" badge on the DeepLearning.AI Forum for participating consistently for 365 consecutive days.
- **August 2024**: Selected as a Mentor by DeepLearning.AI and Coursera for the [`Tensorflow Developer Professional Certificate`](https://www.coursera.org/professional-certificates/tensorflow-in-practice) as a result of my insightful contributions as a course tester.
- **November 2023**: Presented our research paper: Analyzing COVID-19 Vaccination Sentiments in Nigerian Cyberspace: Insights from a Manually Annotated Twitter Dataset, at the International Conference on Computing and Advances in Information Technology (ICCAIT).
- **May 2023**: Came second place in the Cohere AI Hack for developing a language alignment tool.
